### PR TITLE
Force new users to type whole mnemonic before creating a wallet

### PR DESCRIPTION
**Pull request by lukaw3d**
Fixes https://github.com/oasisprotocol/oasis-wallet-web/issues/521

| Before | After |
| --- | --- |
|  |  |

### CODE REVIEW

**Comment by pro-wh** [comment]
the coverage is mad that your test doesn't cover the `onClickOutside` :laughing:

**Review by pro-wh — APPROVED** [review]
alright that looks like an appropriate implementation of the forced enter-the-whole-mnemonic idea

**Review by matevz — CHANGES_REQUESTED** [review]
Generally I like the way this was implemented.

Two details I'd like you to settle:
1. Add the cancel button similar to what we had before: 
image
2. Fix responsiveness (maybe jump to fullscreen and align elements vertically?).
   Before: 
image

   After:
   
image

**Comment by lukaw3d** [comment]
localhost_3000_create-wallet

localhost_3000_create-wallet (1)

localhost_3000_create-wallet (2)

localhost_3000_create-wallet (3)

**Comment by pro-wh** [comment]
dark theme :monocle_face:

**Review by matevz — APPROVED** [review]
Good work!

Just one minor request. Can you make the Confirm mnemonic popup true fullscreen (without any sight of the previous page near the borders) once the window width is smaller than 770px? This behavior was already there before your patch.

**Pull request merged**
