### PR TITLE
Align "Update password" button to the left

### PR DESCRIPTION
**Pull request by lukaw3d**
| Before | After |
| --- | --- |
| localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar) (1)  | localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar)  |

### CODE REVIEW

**Comment by lubej** [comment]
This makes it even more confusing as before. @donouwens can you suggest a button/s layout for this? Making the buttons full width or something, maybe aligning them all to the same side?

**Comment by lukaw3d** [comment]
Should I also remove "Deletion" label?

**Comment by lukaw3d** [comment]
updated
Peek 2024-05-07 02-04

**Review by lubej — APPROVED** [review]

**Comment by lubej** [comment]
> Should I also remove "Deletion" label?

Personally I would remove the label. And place the "Delete profile" button next to "Lock profile" button in the footer. To make it even more consistent with other tabs. wdyt @donouwens?

**Comment by lukaw3d** [comment]
localhost_3000_account_oasis1qrtyn2q78jv6plrmexrsrv4dh89wv4n49udtg2km(extension375x600 + scrollbar)

**Pull request merged**
