### PR TITLE
Rename to ROSE Wallet

### PR DESCRIPTION
**Pull request by lukaw3d**
| Before | After |
| --- | --- |
| localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90(extension360x600) | localhost_3000_(extension360x600) |
| localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90 (1) | localhost_3000_ |
| localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90 | localhost_3000_ (1) |

### CODE REVIEW

**Comment by lukaw3d** [comment]
cc @donouwens

**Review by lubej — APPROVED** [review]
I am just giving LGTM, but would rather see if @buberdds looks at it as well, as he is more familiar with the project.

Mobile part looks good so far, need to check if anything breaks(it shouldn't), but we need to replace the icon + splash as it contains references to the old naming. @donouwens

**Comment by lukaw3d** [comment]
> but we need to replace the icon + splash as it contains references to the old naming

Good point, I wouldn't notice.

I'll rather merge now and fix later - deadline

**Comment by lubej** [comment]
> > but we need to replace the icon + splash as it contains references to the old naming
> 
> Good point, I wouldn't notice.
> 
> I'll rather merge now and fix later - deadline

Sure, no problem. It is not live anyway.

**Pull request merged**
