### PR TITLE
Sort all translations and remove English defaults from translations

### PR DESCRIPTION
**Pull request by lukaw3d**
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/541

### CODE REVIEW

**Comment by matevz** [comment]
Ugh, I wouldn't change non-English translations directly outside of Transifex, because they might get out of sync. Let's wait for Transifex to sync the English source (daily) and see how the export goes. The ordering of terms should be according to English source when you export them.

**Comment by matevz** [comment]
> Ugh, I wouldn't change non-English translations directly outside of Transifex, because they might get out of sync. Let's wait for Transifex to sync the English source (daily) and see how the export goes. The ordering of terms should be according to English source when you export them.

I checked Transifex today and the ordering of non-English terms was automatically synced with the new ordering in English source. However, I noticed some regressions in #541 and made a followup PR to address those in #813 (wrong terms at wrong places, some redundant periods and colons, outdated terms). Once #813 is merged, we should simply grab the translations from Transifex and push them to the main branch.

**Comment by lukaw3d** [comment]
Sounds good

**Comment by matevz** [comment]
Some updates:
- Slovenian language is ready to grab from Transifex.
- Turkish doesn't have a maintainer so you can just download it from Transifex as it is (with sorted terms).
- Raphael will translate the missing 20 terms in French in the following days, so you should wait for him and put it in this PR.
- Feel free to remove German leftovers from the codebase since it's just some i18next mock and has nothing to do with the actual translation.
- It seems the "Download for use" behavior in Transifex for JSON key-value format is "Replace untranslated terms with source". See https://docs.transifex.com/formats/json#section-parser-behaviour . I'm not sure why that is default, but it has to do something with i18next, because .po gettext format I use in other projects behaves differently.

**Comment by matevz** [comment]
Slovenian, Turkish and French are now ready to be merged from Transifex.

**Pull request closed without merging**
