### PR TITLE
Move mobile footer to profile dropdown

### PR DESCRIPTION
**Pull request by buberdds**
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/1952

### CODE REVIEW

**Comment by lubej** [comment]
Wasn't footer supposed to be only visible in settings on both mobile & desktop?

**Comment by buberdds** [comment]
Discussed during UX meeting. We will probably have another "light version" of footer for desktop. Requirements will be updated next week.

**Comment by buberdds** [comment]
new designs 
https://www.figma.com/design/O4ns1tPoFe0MwPjfuigZGH/Wallet-%2F-Address-Book?node-id=332-1258&t=PgFolLK0QWKSiONT-0
- dekstop is always visible but it has a new layout (not sure how it will work for content width 549px - min desktop
- tablet = mobile
- revert GitHub issue https://github.com/oasisprotocol/oasis-wallet-web/issues/1910 and PR (show/hide)
- current footer moved to settings for opened mobile 
- keep current footer for mobile not opened account

**Comment by buberdds** [comment]
need to sync with Don as desktop variant for an opened account looks weird to me

**Comment by buberdds** [comment]
ready for review

**Review by lukaw3d — APPROVED** [review]

**Pull request merged**
