### PR TITLE
Account switching issue - wrong account's details are displayed

### PR DESCRIPTION
**Pull request by buberdds**
Closes https://github.com/oasisprotocol/oasis-wallet-web/issues/267.

### CODE REVIEW

**Review by pro-wh — APPROVED** [review]
this should do for now, thanks for the fix

although now that I really look at this, as well as the original code, it seems unidiomatic for us to be defining this kind of "URL follows selected wallet" kind of invariant by coding it imperatively in this "select a wallet then push URL" way. you've moved it into the consequence of a `takeEvery`, at least. doing the `push` in a 'later' `takeEvery(walletActions.walletSelected, ...)` might be nice too, unless that's taking things too far.

@Esya feel free to weigh in too if you have the time to look

**Comment by buberdds** [comment]
Yeah I was trying to fix the issue without larger refactor as I am not familiar with the app yet.

After reading your comment I think you are correct. It all should work other way around where wallet dropdown/switcher would use router NavLink instead of dispatching current redux action. The problem is that current main wallet url handles different app states one for a default preview and one for selected wallet and selected wallet requires opening a wallet first. Maybe app need a different url for selected wallet where in a case of missing wallet user would go through "Open wallet" step?

**Comment by pro-wh** [comment]
gonna try rebasing and merging

**Comment by pro-wh** [comment]
alright, merged!

> The problem is that current main wallet url handles different app states one for a default preview and one for selected wallet and selected wallet requires opening a wallet first. Maybe app need a different url for selected wallet where in a case of missing wallet user would go through "Open wallet" step?

Thanks for the additional analysis on this. I'll take this into account if we get into discussing a larger rework of this. Using a different URL for users' wallets is something we'll consider. I wonder if we might alternatively try to unify more of the functionality actually to reduce the differences though. It should only come down to whether or not you can sign transactions, after all.

**Comment by tjanez** [comment]
> Thanks for the additional analysis on this. I'll take this into account if we get into discussing a larger rework of this. Using a different URL for users' wallets is something we'll consider. I wonder if we might alternatively try to unify more of the functionality actually to reduce the differences though. It should only come down to whether or not you can sign transactions, after all.

@pro-wh, can you file this as an issue so it doesn't get lost?

**Comment by pro-wh** [comment]
sure thing

**Pull request merged**
