### PR TITLE
Test that generated mnemonics contain more than 32 bits of entropy

### PR DESCRIPTION
**Pull request by lukaw3d**

### CODE REVIEW

**Comment by pro-wh** [comment]
image

image

**Comment by pro-wh** [comment]
oh wait it's a playwright test

**Comment by pro-wh** [comment]
image


>   31 skipped
  6 passed (18.9s)
Done in 20.11s.

oo it did not run nor flag a failure

**Comment by lukaw3d** [comment]
uuuh something is wrong
image

**Comment by lukaw3d** [comment]
It's an upstream playwright bug

**Comment by doperiddle** [comment]
What is that?

Mark D Dannenbaum

**Comment by lukaw3d** [comment]
Fixed that in https://github.com/oasisprotocol/oasis-wallet-web/pull/1588

**Review by pro-wh — APPROVED** [review]
not against this test, but we don't re-seed between each of these 250,000 trials. that mersenne twister implementation would have also generated as many unique mnemonics sequentially, wouldn't it?

**Comment by lukaw3d** [comment]
I'm not sure / I don't have enough background. But this fails, so it probably re-seeds:
```ts
const a = require('@trustwallet/wallet-core'); /* 3.1.0 */
(async () => {
  const wasm = await a.initWasm()
  const generatedMnemonics = new Set([...new Array(250_000)].map(() => wasm.HDWallet.create(256, 'password').mnemonic()))
  console.log(generatedMnemonics.size)
  // 249995 (takes 30min)
})()
```

**Comment by pro-wh** [comment]
https://github.com/trustwallet/wallet-core/blob/3.1.0/wasm/src/Random.cpp#L20

woa it does re-seed. not just for every call into wasm, but for every request for random bytes

**Pull request merged**
